# Generated by Django 4.0.2 on 2022-02-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('birthday', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('birthday', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='movieCategories',
        ),
        migrations.RenameField(
            model_name='moviecategories',
            old_name='name',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='age',
            field=models.IntegerField(default=1, verbose_name=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movieActor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.actor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movieCharacter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movieDirector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.director'),
            preserve_default=False,
        ),
    ]
