# Generated by Django 4.0.2 on 2022-02-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_actor_character_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movieActor',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movieCategories',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movieCharacter',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movieDirector',
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(to='api.MovieCategories'),
        ),
        migrations.AddField(
            model_name='movie',
            name='characters',
            field=models.ManyToManyField(to='api.Character'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(to='api.Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age',
            field=models.IntegerField(verbose_name=4),
        ),
    ]
